sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cp ../linpack-single.cpp .
  - cp ../linpack-double.cpp .
  - g++ -o linpack-single  linpack-single.cpp
  - g++ -o linpack-double  linpack-double.cpp
  - ls -al
  - ./linpack-single
  - ./linpack-double
  
 

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
